#客服告警 config 2024.02.23 與正式區同步

check.keyword=\u5f15\u64ce\u639b\u6a5f,\u5f15\u64ce\u540c\u6b65,\u5c0fi\u7570\u5e38,\u7cfb\u7d71\u7570\u5e38,\u8cfd\u5fae\u7570\u5e38

#"nomatch掛機", "nomatch轉真人", "2次nomatch, "反對問2次錯誤事件","其他錯誤事件", "第一段nomatch","第二段nomatch", 
#"AInomatch", "nomatch兩次", "接通無法辨識","引擎掛機","引擎同步","小i異常" 
#20230509 新增關鍵字 "系統異常","賽微異常"
#20230511 確認最新版關鍵字 "引擎掛機","引擎同步","小i異常","系統異常","賽微異常" 

#為解決value注入中文問題，此部分改為unicode
#log.fileHandler=/gcti/checknomatchtest/check.log


#DB-------------------

#客服告警 config
#Hualiteq123$(對照用，上正式區要刪除）

#gcti-uat(對照用，上uat&prod要刪除）
#datasource.url=jdbc:sqlserver://172.16.241.195:3301;DatabaseName=gcti_ivr_csr
#datasource.username=GenesysCTI
#datasource.password=Password01

#gcti-uat加密
datasource.url=qfxehk0wSyMbjXvHRQrVzSuzWNo2huDGZeMzkT1NO2OPN+i5cY1xtNUDZXs1Iq54R83w2MUZPTuMLdOw4E/FnA==
datasource.username=FZHhtX27NOCSweCPLueVwA==
datasource.password=GKIYwCa4Vd5MX2VYMF27Eg==

#gcti-prod(對照用，上uat&prod要刪除）
#datasource.url=jdbc:sqlserver://172.16.193.21:3301;DatabaseName=gcti_ivr_csr
#datasource.username=GenesysCTI
#datasource.password=PE08bu49$

#gcti-prod加密
#datasource.url=qfxehk0wSyMbjXvHRQrVzVcdN1hrD2/saW5oj2YzhN+wJT9pJe6TrnzxXUwP0Dp+g4UvOXSJ//pOh/MMtXkARg==
#datasource.username=FZHhtX27NOCSweCPLueVwA==
#datasource.password=tf2R5lFkQJegqdXo/Qb71A==

#oracle-uat(對照用，上uat&prod要刪除）
#datasource.url2=jdbc:oracle:thin:@//172.17.241.230:5211/TCTI
#datasource.username2=CREDIT_CTI
#datasource.password2=CREDITCTI
#oracle-uat加密
datasource.url2=b5Z2FSJ7B77JIHsgAFuQErZIYHoomz7ZLOELkuxibrHk8kr+2kx8d9YSiMC5HZPn
datasource.username2=EofhR6E4Vebr4j4yA2pJ+A==
datasource.password2=3voBsqh4pxC2KYY12KGt4w==

#oracle-pord(對照用，上正式區要刪除，注意是PTCI）
#datasource.url2=jdbc:oracle:thin:@//172.17.201.120:5211/PCTI
#datasource.username2=CREDIT_CTI
#datasource.password2=CREDITCTI

#oracle-pord加密
#datasource.url2=b5Z2FSJ7B77JIHsgAFuQEjX1MkgdOZJGChYizk2k5mo8Z92e/eGLtAczw91OgruR
#datasource.username2=EofhR6E4Vebr4j4yA2pJ+A==
#datasource.password2=3voBsqh4pxC2KYY12KGt4w==

#以下為客服AI設定
#告警驗證次數
check.allow=3

#crontab 5分鐘起一次

#sql (全流程偵測
sql.ResultSet=SELECT TOP (3) [CallUUID],[Begin_Time],[Flow_ID],[Reason_Memo] FROM [gcti_ivr_csr].[dbo].[IVR_Call_Records]where Begin_Time between(SELECT CONVERT(DATETIME,CONVERT(VARCHAR(10),GETDATE(),120))) and (SELECT DATEADD(SS,-1,DATEADD(DD,1,CONVERT(DATETIME,CONVERT(VARCHAR(10),GETDATE(),120))))) order by Begin_Time desc

#告警寄送清單
email.list=NBUTTW01880@fubon.com,control.desk@fubon.com,control.bank@fubon.com,jell.lee@fubon.com,mingshing.li@fubon.com,mingshing.li@fubon.com,jasmine.fy.chou@fubon.com,marc.lang@fubon.com,antony.hsieh@fubon.com,vivijen.tseng@fubon.com,art.chang@fubon.com,walker.lin@fubon.com,ebecca.chang@fubon.com,cherry.kwan@fubon.com,yafen.hsu@fubon.com,garfield.chen@fubon.com

phone.list=0983092709,0958303033,0920192410,0982022755,0920065262,0938935888,0988389918,0939804914,0919512905,0926669747,0922909901,0958044489,0955091931,0939898388,0972180896

#告警寄送清單:
# 1. user-群組信箱 NBUTTW01880@fubon.com 0983092709 //20240222修正
# 2. CC中控公務信箱 control.desk@fubon.com 0958303033,
# 3. BK中控公務信箱 control.bank@fubon.com 0920192410,
# 4. user-李雯鈺 jell.lee@fubon.com 0982022755,
# 5. IT-後勤-李明星 mingshing.li@fubon.com 0920065262,
# 6. IT-後勤-周芳妤 jasmine.fy.chou@fubon.com 0938935888,
# 7. IT-後勤-郎浩雲 marc.lang@fubon.com 0988389918,
# 8. IT-後勤-謝士偉 antony.hsieh@fubon.com 0939804914,
# 9. IT-後勤-曾淑芬 vivijen.tseng@fubon.com 0919512905,
# 10. IT-數金-張志誥 art.chang@fubon.com 0926669747, 
# 11. IT-數金-林立燊 walker.lin@fubon.com 0922909901,
# 12. IT-數金-張瓊方 rebecca.chang@fubon.com 0958044489,

#20240111 (新增
# 13. user-卡處-關慧婷 cherry.kwan@fubon.com 0955091931,
# 14. user-卡處-許雅芬 yafen.hsu@fubon.com 0939898388,
# 15. user-卡處-陳靜怡 garfield.chen@fubon.com 0972180896,
#刪除 IT-後勤-陳彥麒 

#20240222 修正 user-群組信箱 NBG01901880@fubon.com -> NBUTTW01880@fubon.com
