#測試區

check.keyword=\u5f15\u64ce\u639b\u6a5f,\u5f15\u64ce\u540c\u6b65,\u5c0fi\u7570\u5e38,\u7cfb\u7d71\u7570\u5e38,\u8cfd\u5fae\u7570\u5e38

#"nomatch掛機", "nomatch轉真人", "2次nomatch, "反對問2次錯誤事件","其他錯誤事件", "第一段nomatch","第二段nomatch", 
#"AInomatch", "nomatch兩次", "接通無法辨識","引擎掛機","引擎同步","小i異常" 
#20230509 新增關鍵字 "系統異常","賽微異常"
#20230511 確認最新版關鍵字 "引擎掛機","引擎同步","小i異常","系統異常","賽微異常" 

#為解決value注入中文問題，此部分改為unicode
#log.fileHandler=/gcti/checknomatchtest/check.log

#gcti正式
#datasource.url=jdbc:sqlserver://172.16.193.21:3301;DatabaseName=gcti_ivr_csr
#datasource.username=GenesysCTI
#datasource.password=PE08bu49$
#gcti測試
datasource.url=jdbc:sqlserver://172.16.241.195:3301;DatabaseName=gcti_ivr_csr
datasource.username=GenesysCTI
datasource.password=Password01
#gcti本機
#datasource.url=jdbc:sqlserver://localhost:1433;databaseName=gcti_ivr_csr
#datasource.username=admin
#datasource.password=admin

#oracle測試
datasource.url2=jdbc:oracle:thin:@//172.17.241.230:5211/TCTI
datasource.username2=CREDIT_CTI
datasource.password2=CREDITCTI

#oracle正式
#datasource.url2=jdbc:oracle:thin:@//172.17.201.120:5211/TCTI
#datasource.username2=CREDIT_CTI
#datasource.password2=CREDITCTI


#以下為客服AI設定
#告警驗證次數
check.allow=3

#若sql更動請改這行，此為「排除」流程清單
sql.ResultSet=SELECT TOP (3) [CallUUID],[Begin_Time],[Flow_ID],[Reason_Memo] FROM [gcti_ivr_csr].[dbo].[IVR_Call_Records]where not [Flow_ID] in('REC1-1','REC1-2','REC1-3','REC1-4','REC1-7','REC1-8','REC1-9','REC1-10','REC1-11','REC1-12','REC2-3','REC3-5','REC3-7','REC3-8','REC5-2') and Begin_Time between(SELECT CONVERT(DATETIME,CONVERT(VARCHAR(10),GETDATE(),120))) and (SELECT DATEADD(SS,-1,DATEADD(DD,1,CONVERT(DATETIME,CONVERT(VARCHAR(10),GETDATE(),120))))) order by Begin_Time desc

#告警寄送清單
email.list=mingchuan.tsai@fubon.com,cathy.chu@fubon.com,hsiuting.chen@fubon.com,antony.hsieh@fubon.com,yenan.chen@fubon.com,mingshing.li@fubon.com,art.chang@fubon.com,walker.lin@fubon.com,jeff.dr.tsai@fubon.com
phone.list=0983092709,0958303033,0920192410,0939804914,0933892734,0920065262,0926669747,0922909901,0919587570

#告警寄送清單:
# 蔡明娟 mingchuan.tsai@fubon.com 0983092709 ,朱晏宜 cathy.chu@fubon.com 0958303033, 陳秀婷 hsiuting.chen@fubon.com 0920192410
# 謝士偉 antony.hsieh@fubon.com 0939804914  陳彥安 yenan.chen@fubon.com 0933892734, 李明星 mingshing.li@fubon.com 0920065262
# 張志誥 art.chang@fubon.com 0926669747 林立燊 walker.lin@fubon.com 0922909901 蔡典融 jeff.dr.tsai@fubon.com 0919587570


