#客服告警 config
check.keyword=\u5f15\u64ce\u639b\u6a5f,\u5f15\u64ce\u540c\u6b65,\u7570\u5e38
#20230511 確認最新版關鍵字 "引擎掛機","引擎同步","小i異常","系統異常","賽微異常" 
#20241120 更新關鍵字: "引擎掛機","引擎同步","呼叫","異常"
#20241226 更新暫解關鍵字: "引擎掛機","引擎同步","異常"
#為解決value注入中文問題，此部分改為unicode

#DB-------------------

#gcti-prod加密
link.config1=dqVmv9fNQEmIOQiCbqbs/zulCx1Q2ImrdZKHtUpsqls7RaacJMA85UeU99XH0/mKVasrtXjWfh14qZn6mjOTS6Zy+quPYS2L/XIjIdTBPdyvFVvV1ID7csA=
link.config2=nZRhwcBptZGzsRioaFUHKUwP7RFvI8ihlvfKoecjovBBS3ZbAv4=
link.config3=a1d4GL40TeNbgFdBjv7vIAuDCWBrXAdtGX4YONMUth8xsLgvMw==

#oracle-prod加密
link.config21=3iwcs4aannU7LFKy0NYqvG5i/HcDXc37FJpoqjh25MIwWw1XmjJnpGheDZ7htBL2WjRrjUXG6GT0XK//OccRsJbds4W289hu
link.config22=hWa8xhYPdX/VfrPLkROy5jg8E82e3idpWDxlGB76FOePp+jg2Lk=
link.config23=bqbHoIixSJa/b4WcXG0AJ86cUXLocRqaGO1xSV5ua+FPPPpOKA==

#以下為客服AI設定
#告警驗證次數
check.allow=3

#遵法告警驗證次數
rec.check.time=1
#unit現版本支援 : hour, day , 預設為minute
rec.check.unit=hour

#crontab 5分鐘起一次

#sql (全流程偵測
sql.Select=SELECT TOP(?) 
sql.SelectValue=icr.[CallUUID],icr.[Begin_Time],icr.[Flow_ID],icr.[Reason_Memo] 
sql.From=FROM [gcti_ivr_csr].[dbo].[IVR_Call_Records] as icr 
sql.JoinREC=INNER JOIN [gcti_ivr_csr].[dbo].[IVR_Flow_Setting] as ifs ON icr.[Flow_ID] = ifs.[Flow_ID] 
sql.Where=where Begin_Time between(SELECT CONVERT(DATETIME,CONVERT(VARCHAR(10),GETDATE(),120))) and (SELECT DATEADD(SS,-1,DATEADD(DD,1,CONVERT(DATETIME,CONVERT(VARCHAR(10),GETDATE(),120))))) and icr.[End_Time] is not null and icr.[Reason_Memo] is not null
sql.WhereAndREC=and ifs.[Flow_Type] = 'R' 
sql.Order=order by Begin_Time desc 
sql.ResultSet=SELECT TOP (3) [CallUUID],[Begin_Time],[Flow_ID],[Reason_Memo] FROM [dbo].[IVR_Call_Records] where Begin_Time between(SELECT CONVERT(DATETIME,CONVERT(VARCHAR(10),GETDATE(),120))) and (SELECT DATEADD(SS,-1,DATEADD(DD,1,CONVERT(DATETIME,CONVERT(VARCHAR(10),GETDATE(),120))))) and [End_Time] is not null and [Reason_Memo] is not null  order by Begin_Time desc

#告警寄送清單
email.list=NBUTTW01880@fubon.com,control.desk@fubon.com,control.bank@fubon.com,jell.lee@fubon.com,antony.hsieh@fubon.com,saint.chang@fubon.com,jasmine.fy.chou@fubon.com,chengchang.wu@fubon.com,jacky.j.chang@fubon.com,nelson.yw.chen@fubon.com,walker.lin@fubon.com,rebecca.chang@fubon.com,cherry.kwan@fubon.com,yafen.hsu@fubon.com,garfield.chen@fubon.com,chiahua.chang@fubon.com
phone.list=0966103265,0958303033,0920192410,0982022755,0939804914,0920535443,0938935888,0986011137,0930982213,0933797100,0922909901,0958044489,0955091931,0939898388,0972180896,0935225680

#20250103 - 張志誥替換陳昱維